name: Trigger CircleCI from Comment

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  execute:
    # if: ${{ github.event.label.name == 'run ci' }}
    # if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Capture triggering branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Dump payload
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Trigger CircleCI build-beta workflow.
        uses: promiseofcake/circleci-trigger-action@v1
        with:
          user-token: ${{ secrets.CIRCLECI_TOKEN }}
          project-slug: salesforce-ux/design-system-starter-kit
          # branch: ${{ env.BRANCH_NAME }}
          branch: ${{ github.head_ref }}
          payload: '{"run_commented_workflow": true}'
